### ISSUE TITLE
TypeError when running demo

### ISSUE THREAD

**Issue by bubonicfred** [DIYer22/process_raw#1]
When running demo (and also in my own code) I receive the following error

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "~/.local/lib/python3.8/site-packages/process_raw/process_raw.py", line 186, in <module>
    raw = DngFile.test()
  File "~/.local/lib/python3.8/site-packages/process_raw/process_raw.py", line 173, in test
    DngFile.save(dngp + "-save.dng", raw, bit=dng.bit, pattern=dng.pattern)
  File "~/.local/lib/python3.8/site-packages/process_raw/process_raw.py", line 115, in save
    RAW2DNG().convert(
TypeError: convert() got an unexpected keyword argument 'tags'
```

**Comment by DIYer22** [comment]
The probrom is pidng's gets a upgrade and break old API

I adapted to the new version of pidng, and fix the problem

Please update your process_raw
```
pip install process_raw>=0.2.0
```

**Comment by DRCRecoveryData** [comment]
> The probrom is pidng's gets a upgrade and break old API
> 
> I adapted to the new version of pidng, and fix the problem
> 
> Please update your process_raw
> 
> ```
> pip install process_raw>=0.2.0
> ```

Hi,

I have repair some CR2 corrupted by fix header but the CR2 still content the image from old file and can't import to photoshop, how can i convert it to dng with your library?

Here are my sample file:

https://gofile.io/d/Ae6nu2

1. I cut from start of file of 2V3A1752.CR2 to offset FFD8FFC4 of: "2V3A1752.CR2" ( 1 )
2. I cut from offset FFD8FFC4 of: "2V3A7514.CR2.vvew" to end of file ( 2 )
3.  I merger ( 1 ) ( 2 ) save to new file
4.  But the repaired cr2 have old thumbnail and image from "2V3A1752.CR2" so i want to convert it to DNG to see raw image of "2V3A7514.CR2.vvew" and can import it to photoshop

**Comment by DIYer22** [comment]
@cuuhodrc  I'm not good at image coding, so I can't help.
You can go to these two libraries for help:
- [rawpy](https://github.com/letmaik/rawpy): For read .dng file
- [PiDNG](https://github.com/schoolpost/PiDNG): For save raw as .dng file
